//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RuleEngine
{
    public partial class OldStatus
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string StatusName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<VehicleStatus> tlkpVehicleStatus
        {
            get
            {
                if (_tlkpVehicleStatus == null)
                {
                    var newCollection = new FixupCollection<VehicleStatus>();
                    newCollection.CollectionChanged += FixuptlkpVehicleStatus;
                    _tlkpVehicleStatus = newCollection;
                }
                return _tlkpVehicleStatus;
            }
            set
            {
                if (!ReferenceEquals(_tlkpVehicleStatus, value))
                {
                    var previousValue = _tlkpVehicleStatus as FixupCollection<VehicleStatus>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptlkpVehicleStatus;
                    }
                    _tlkpVehicleStatus = value;
                    var newValue = value as FixupCollection<VehicleStatus>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptlkpVehicleStatus;
                    }
                }
            }
        }
        private ICollection<VehicleStatus> _tlkpVehicleStatus;
    
        public virtual ICollection<VehicleStatus> tlkpVehicleStatus1
        {
            get
            {
                if (_tlkpVehicleStatus1 == null)
                {
                    var newCollection = new FixupCollection<VehicleStatus>();
                    newCollection.CollectionChanged += FixuptlkpVehicleStatus1;
                    _tlkpVehicleStatus1 = newCollection;
                }
                return _tlkpVehicleStatus1;
            }
            set
            {
                if (!ReferenceEquals(_tlkpVehicleStatus1, value))
                {
                    var previousValue = _tlkpVehicleStatus1 as FixupCollection<VehicleStatus>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptlkpVehicleStatus1;
                    }
                    _tlkpVehicleStatus1 = value;
                    var newValue = value as FixupCollection<VehicleStatus>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptlkpVehicleStatus1;
                    }
                }
            }
        }
        private ICollection<VehicleStatus> _tlkpVehicleStatus1;

        #endregion
        #region Association Fixup
    
        private void FixuptlkpVehicleStatus(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (VehicleStatus item in e.NewItems)
                {
                    item.tlkpStatus = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (VehicleStatus item in e.OldItems)
                {
                    if (ReferenceEquals(item.tlkpStatus, this))
                    {
                        item.tlkpStatus = null;
                    }
                }
            }
        }
    
        private void FixuptlkpVehicleStatus1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (VehicleStatus item in e.NewItems)
                {
                    item.tlkpStatus1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (VehicleStatus item in e.OldItems)
                {
                    if (ReferenceEquals(item.tlkpStatus1, this))
                    {
                        item.tlkpStatus1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
