//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RuleEngine
{
    public partial class TransitionSpecification
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int StatusTransitionId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string RsBracketNo
        {
            get;
            set;
        }
    
        public virtual string RuleConnectors
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<RuleStatement> tblRuleStatements
        {
            get
            {
                if (_tblRuleStatements == null)
                {
                    var newCollection = new FixupCollection<RuleStatement>();
                    newCollection.CollectionChanged += FixuptblRuleStatements;
                    _tblRuleStatements = newCollection;
                }
                return _tblRuleStatements;
            }
            set
            {
                if (!ReferenceEquals(_tblRuleStatements, value))
                {
                    var previousValue = _tblRuleStatements as FixupCollection<RuleStatement>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptblRuleStatements;
                    }
                    _tblRuleStatements = value;
                    var newValue = value as FixupCollection<RuleStatement>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptblRuleStatements;
                    }
                }
            }
        }
        private ICollection<RuleStatement> _tblRuleStatements;
    
        public virtual ICollection<StatusTransition> tblStatusTransitions
        {
            get
            {
                if (_tblStatusTransitions == null)
                {
                    var newCollection = new FixupCollection<StatusTransition>();
                    newCollection.CollectionChanged += FixuptblStatusTransitions;
                    _tblStatusTransitions = newCollection;
                }
                return _tblStatusTransitions;
            }
            set
            {
                if (!ReferenceEquals(_tblStatusTransitions, value))
                {
                    var previousValue = _tblStatusTransitions as FixupCollection<StatusTransition>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptblStatusTransitions;
                    }
                    _tblStatusTransitions = value;
                    var newValue = value as FixupCollection<StatusTransition>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptblStatusTransitions;
                    }
                }
            }
        }
        private ICollection<StatusTransition> _tblStatusTransitions;

        #endregion
        #region Association Fixup
    
        private void FixuptblRuleStatements(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RuleStatement item in e.NewItems)
                {
                    item.tblTransitionSpecification = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RuleStatement item in e.OldItems)
                {
                    if (ReferenceEquals(item.tblTransitionSpecification, this))
                    {
                        item.tblTransitionSpecification = null;
                    }
                }
            }
        }
    
        private void FixuptblStatusTransitions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StatusTransition item in e.NewItems)
                {
                    item.tblTransitionSpecification = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StatusTransition item in e.OldItems)
                {
                    if (ReferenceEquals(item.tblTransitionSpecification, this))
                    {
                        item.tblTransitionSpecification = null;
                    }
                }
            }
        }

        #endregion
    }
}
